apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  labels:
    app: nginx
spec:
  type: NodePort  # Exposes the service on each Node's IP at a static port
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Port on each node (range: 30000-32767)
    protocol: TCP
    name: http
