apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-demo-service
  labels:
    app: lb-demo
spec:
  type: LoadBalancer
  selector:
    app: lb-demo
  ports:
  - port: 80
    targetPort: 9376
    protocol: TCP
  sessionAffinity: None  # Round-robin load balancing (default)
